version: '3.6'

services:
  host1:
    image: scion_host:latest
    container_name: host1
    environment:
      - SUPERVISOR_PROCESS_GROUP=as1-ff00_0_1
    volumes:
      - ${SCION_ROOT:?}/bin:/home/scion/scion/bin:ro
      - ${SCION_APPS:?}/bin:/home/scion/scion-apps/bin:ro
      - ${SCION_ROOT:?}/gen:/home/scion/scion/gen:ro
      - ${SCION_ROOT:?}/gen-cache:/home/scion/scion/gen-cache
      - ${SCION_ROOT:?}/gen-certs:/home/scion/scion/gen-certs
      - ${SCION_ROOT:?}/logs:/home/scion/scion/logs
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      # link1:
      #   ipv4_address: 10.1.1.2
      link2:
        ipv4_address: 10.1.2.2
  host2:
    image: scion_host:latest
    container_name: host2
    environment:
      - SUPERVISOR_PROCESS_GROUP=as1-ff00_0_2
    volumes:
      - ${SCION_ROOT:?}/bin:/home/scion/scion/bin:ro
      - ${SCION_APPS:?}/bin:/home/scion/scion-apps/bin:ro
      - ${SCION_ROOT:?}/gen:/home/scion/scion/gen:ro
      - ${SCION_ROOT:?}/gen-cache:/home/scion/scion/gen-cache
      - ${SCION_ROOT:?}/gen-certs:/home/scion/scion/gen-certs
      - ${SCION_ROOT:?}/logs:/home/scion/scion/logs
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      # link1:
      #   ipv4_address: 10.1.1.3
      link3:
        ipv4_address: 10.1.3.3
  host3:
    image: scion_host:latest
    container_name: host3
    environment:
      - SUPERVISOR_PROCESS_GROUP=as1-ff00_0_3
    volumes:
      - ${SCION_ROOT:?}/bin:/home/scion/scion/bin:ro
      - ${SCION_APPS:?}/bin:/home/scion/scion-apps/bin:ro
      - ${SCION_ROOT:?}/gen:/home/scion/scion/gen:ro
      - ${SCION_ROOT:?}/gen-cache:/home/scion/scion/gen-cache
      - ${SCION_ROOT:?}/gen-certs:/home/scion/scion/gen-certs
      - ${SCION_ROOT:?}/logs:/home/scion/scion/logs
    networks:
      link2:
        ipv4_address: 10.1.2.4
      link4:
        ipv4_address: 10.1.4.4
  host4:
    image: scion_host:latest
    container_name: host4
    environment:
      - SUPERVISOR_PROCESS_GROUP=as1-ff00_0_4
    volumes:
      - ${SCION_ROOT:?}/bin:/home/scion/scion/bin:ro
      - ${SCION_APPS:?}/bin:/home/scion/scion-apps/bin:ro
      - ${SCION_ROOT:?}/gen:/home/scion/scion/gen:ro
      - ${SCION_ROOT:?}/gen-cache:/home/scion/scion/gen-cache
      - ${SCION_ROOT:?}/gen-certs:/home/scion/scion/gen-certs
      - ${SCION_ROOT:?}/logs:/home/scion/scion/logs
    networks:
      link3:
        ipv4_address: 10.1.3.5
      link4:
        ipv4_address: 10.1.4.5

networks:
  # link1:
  #   name: link1
  #   ipam:
  #     config:
  #       - subnet: 10.1.1.0/24
  link2:
    name: link2
    ipam:
      config:
        - subnet: 10.1.2.0/24
  link3:
    name: link3
    ipam:
      config:
        - subnet: 10.1.3.0/24
  link4:
    name: link4
    ipam:
      config:
        - subnet: 10.1.4.0/24
